// Script to sync existing hackathons and projects to CalendarEvent table
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function syncAll() {
    console.log('Starting calendar sync...');

    // Get all hackathons
    const hackathons = await prisma.hackathon.findMany();
    console.log(`Found ${hackathons.length} hackathons`);

    for (const h of hackathons) {
        // Delete existing auto-generated events
        await prisma.calendarEvent.deleteMany({
            where: { hackathonId: h.id, autoGenerated: true }
        });

        const events: Array<{
            title: string;
            date: Date;
            type: string;
            priority: string;
            autoGenerated: boolean;
            sourceType: string;
            eventKind: string;
            hackathonId: string;
            description: string;
        }> = [];

        if (h.registrationDeadline) {
            events.push({
                title: `📝 ${h.name} - Registration Deadline`,
                date: h.registrationDeadline,
                type: 'HACKATHON',
                priority: 'HIGH',
                autoGenerated: true,
                sourceType: 'hackathon',
                eventKind: 'registration',
                hackathonId: h.id,
                description: `Auto-generated from hackathon: ${h.name}`
            });
        }

        if (h.submissionDeadline) {
            events.push({
                title: `🚀 ${h.name} - Submission Deadline`,
                date: h.submissionDeadline,
                type: 'HACKATHON',
                priority: 'HIGH',
                autoGenerated: true,
                sourceType: 'hackathon',
                eventKind: 'submission',
                hackathonId: h.id,
                description: `Auto-generated from hackathon: ${h.name}`
            });
        }

        if (h.eventStartDate) {
            events.push({
                title: `⚡ ${h.name} - Event Start`,
                date: h.eventStartDate,
                type: 'HACKATHON',
                priority: 'HIGH',
                autoGenerated: true,
                sourceType: 'hackathon',
                eventKind: 'event_start',
                hackathonId: h.id,
                description: `Auto-generated from hackathon: ${h.name}`
            });
        }

        if (events.length > 0) {
            await prisma.calendarEvent.createMany({ data: events });
            console.log(`Created ${events.length} events for hackathon: ${h.name}`);
        }
    }

    // Get all projects with deadlines
    const projects = await prisma.project.findMany({ where: { deadline: { not: null } } });
    console.log(`Found ${projects.length} projects with deadlines`);

    for (const p of projects) {
        await prisma.calendarEvent.deleteMany({
            where: { projectId: p.id, autoGenerated: true }
        });

        if (p.deadline) {
            await prisma.calendarEvent.create({
                data: {
                    title: `📅 ${p.name} - Deadline`,
                    date: p.deadline,
                    type: 'PROJECT',
                    priority: 'HIGH',
                    autoGenerated: true,
                    sourceType: 'project',
                    eventKind: 'deadline',
                    projectId: p.id,
                    description: `Auto-generated from project: ${p.name}`
                }
            });
            console.log(`Created event for project: ${p.name}`);
        }
    }

    const total = await prisma.calendarEvent.count();
    console.log(`\n✅ Total calendar events: ${total}`);

    await prisma.$disconnect();
}

syncAll().catch(console.error);
